apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timerapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/wesley-codes/Timer-CI"
    targetRevision: HEAD
    path: timerapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
